### ISSUE TITLE
Problem with text encoding

### ISSUE THREAD

**Issue by vorons** [thingbomb/feedbomb#3]
![2024-09-10 09-21-00](https://github.com/user-attachments/assets/d7d0a9e8-b154-47b7-9eda-5be3f3e7cab7)

**Comment by georg-stone** [comment]
Could you please provide the RSS feed URL so I can take a closer look and debug this issue?

**Comment by vorons** [comment]
> Could you please provide the RSS feed URL so I can take a closer look and debug this issue?

https://nnmclub.to/forum/rssp.xml

**Comment by georg-stone** [comment]
Hmmm... based on my testing, the server successfully fetches the feed, but the response contains those unknown character symbols. This suggests there may be an issue with character encoding on the server or the feed source.

**Comment by vorons** [comment]
Sorry for the delayed response.

This RSS feed uses the `windows-1251` encoding:
```xml
<?xml version="1.0" encoding="windows-1251"?>
```

But the `rss-parser` library only supports those encodings that are natively supported by NodeJS:

https://stackoverflow.com/questions/14551608/list-of-encodings-that-node-js-supports

The developers of `rss-parser` suggest using `iconv`, but I'm not sure it's a good idea.

**Comment by georg-stone** [comment]
Thank you so much! The latest version fixes this issue and works with this text encoding.
